
CREATE SCHEMA IF NOT EXISTS JARDINS_PUBLICS;

USE JARDINS_PUBLICS;

CREATE TABLE IF NOT EXISTS DISTRICTE(
	codi TINYINT UNSIGNED UNIQUE NOT NULL,
    denominacio VARCHAR(100)
    
);

CREATE TABLE IF NOT EXISTS BARRI(
	codi TINYINT UNSIGNED UNIQUE NOT NULL,
    denominacio VARCHAR(100),
    superficie DECIMAL( 9, 2),
    codiDistricte TINYINT UNSIGNED NOT NULL,
    habitants MEDIUMINT UNSIGNED NOT NULL 
);


CREATE TABLE  IF NOT EXISTS SECTOR(
	codi TINYINT UNSIGNED UNIQUE NOT NULL , 
    codiBarri TINYINT UNSIGNED UNIQUE NOT NULL,
    superficie DECIMAL(9,2),
    superficieZonaVerda DECIMAL(9,2)
    );
    
CREATE TABLE IF NOT EXISTS PLANTA(
	codi SMALLINT UNSIGNED UNIQUE NOT NULL,
    nomComu VARCHAR(100) UNIQUE,
    nomCientific VARCHAR(100) UNIQUE,
    condicionsCreixement VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS EMPRESA(
	CIF VARCHAR(9) UNIQUE NOT NULL,
    denominacio VARCHAR(100),
    telefon VARCHAR(9)

);

CREATE TABLE IF NOT EXISTS TREBALLADOR(
	DNI VARCHAR(9) UNIQUE NOT NULL,
    NSS CHAR(9) UNIQUE , 
    telefon VARCHAR(12),
    nom VARCHAR(50),
    cognoms VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS TECNICS(
	DNItreballador VARCHAR(9) UNIQUE NOT NULL,
    especialitzacio VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS JARDINERS(
	DNItreballador VARCHAR(9) UNIQUE NOT NULL,
    competenciesTecniques VARCHAR(255),
    codiSector TINYINT UNSIGNED,
    codiBarri TINYINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS ADMINISTRACIO (
	DNItreballador VARCHAR(9) UNIQUE NOT NULL,
    areaResponsabilitat VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS DISSENY_JARDI(
	codi SMALLINT UNSIGNED UNIQUE NOT NULL,
    denominacio VARCHAR(100),
    ubicacio VARCHAR(255),
    pressupost DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS TROBEM (
	codiPlanta SMALLINT UNSIGNED UNIQUE NOT NULL, 
    codiSector TINYINT UNSIGNED UNIQUE NOT NULL,
    codiBarri  TINYINT UNSIGNED UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPATIBILITAT (
		codiPlanta1 SMALLINT UNSIGNED  NOT NULL,
        codiPlanta2 SMALLINT UNSIGNED  NOT NULL
);

CREATE TABLE IF NOT EXISTS CONCESSIO (
	codiSector TINYINT UNSIGNED NOT NULL,
    codiBarri  TINYINT UNSIGNED NOT NULL,
    `data` DATE UNIQUE NOT NULL,
    CIF VARCHAR(9) UNIQUE NOT NULL, -- NOT NULL NO LLAVE PRIMARIA SI REALCION 1 
    data_fi DATE
);

CREATE TABLE IF NOT EXISTS TREBALLA (
	`data` DATE NOT NULL, 
    DNI VARCHAR(9) NOT NULL,
    CIF VARCHAR(9) UNIQUE NOT NULL,
    data_fi DATE
);

CREATE TABLE IF NOT EXISTS TREBALLEN (
	codi SMALLINT UNSIGNED NOT NULL, 
    DNItecnic VARCHAR(9) NOT NULL
);

ALTER TABLE DISTRICTE 
ADD CONSTRAINT districte_pk PRIMARY KEY (codi);

ALTER TABLE BARRI
ADD CONSTRAINT barri_pk PRIMARY KEY (codi);

ALTER TABLE SECTOR
ADD CONSTRAINT sector_pk PRIMARY KEY (codi, codiBarri);

ALTER TABLE PLANTA
ADD CONSTRAINT planta_pk PRIMARY KEY (codi);

ALTER TABLE EMPRESA 
ADD CONSTRAINT empresa_pk PRIMARY KEY (CIF);

ALTER TABLE TREBALLADOR
ADD CONSTRAINT treballador_pk PRIMARY KEY(DNI);

ALTER TABLE TECNICS
ADD CONSTRAINT tecnics_pk PRIMARY KEY (DNItreballador);

ALTER TABLE JARDINERS
ADD CONSTRAINT jardiners_pk PRIMARY KEY (DNItreballador);

ALTER TABLE ADMINISTRACIO
ADD CONSTRAINT administracio_pk PRIMARY KEY (DNItreballador);

ALTER TABLE DISSENY_JARDI
ADD CONSTRAINT disseny_jardi_pk PRIMARY KEY (codi);

ALTER TABLE TROBEM
ADD CONSTRAINT trobem_pk PRIMARY KEY (codiPlanta, codiSector, codiBarri);

ALTER TABLE COMPATIBILITAT
ADD CONSTRAINT compatibilitat_pk PRIMARY KEY (codiPlanta1, codiPlanta2);

ALTER TABLE CONCESSIO 
ADD CONSTRAINT concessio_pk PRIMARY KEY (codiSector, codiBarri, `data`);

ALTER TABLE TREBALLA
ADD CONSTRAINT treballa_pk PRIMARY KEY (`data`, DNI, CIF);

ALTER TABLE TREBALLEN
ADD CONSTRAINT treballen_pk PRIMARY KEY (codi, DNItecnic);

-- FOREING KEYS

ALTER TABLE BARRI
ADD FOREIGN KEY (codiDistricte) REFERENCES DISTRICTE (codi);

ALTER TABLE SECTOR
ADD FOREIGN KEY (codiBarri) REFERENCES BARRI (codi);

ALTER TABLE TECNICS
ADD FOREIGN KEY (DNItreballador) REFERENCES TREBALLADOR (DNI);

ALTER TABLE JARDINERS
ADD FOREIGN KEY (DNItreballador) REFERENCES TREBALLADOR (DNI),
ADD FOREIGN KEY (codiSector) REFERENCES SECTOR (codi),
ADD FOREIGN KEY (codiBarri) REFERENCES SECTOR (codiBarri);

ALTER TABLE ADMINISTRACIO
ADD FOREIGN KEY (DNItreballador) REFERENCES TREBALLADOR (DNI);

ALTER TABLE TROBEM
ADD FOREIGN KEY (codiPlanta) REFERENCES PLANTA (codi),
ADD FOREIGN KEY (codiSector) REFERENCES SECTOR (codi),
ADD FOREIGN KEY (codiBarri)  REFERENCES SECTOR (codiBarri);

ALTER TABLE COMPATIBILITAT
ADD FOREIGN KEY (codiPlanta1) REFERENCES PLANTA (codi),
ADD FOREIGN KEY (codiPlanta2) REFERENCES PLANTA (codi);

ALTER TABLE CONCESSIO 
ADD FOREIGN KEY (codiSector) REFERENCES SECTOR (codi),
ADD FOREIGN KEY (codiBarri) REFERENCES SECTOR (codiBarri),
ADD FOREIGN KEY (CIF) REFERENCES EMPRESA (CIF);

ALTER TABLE TREBALLA
ADD FOREIGN KEY (DNI) REFERENCES TREBALLADOR (DNI),
ADD FOREIGN KEY (CIF) REFERENCES EMPRESA (CIF);

ALTER TABLE TREBALLEN
ADD FOREIGN KEY (codi) REFERENCES DISSENY_JARDI (codi),
ADD FOREIGN KEY (DNItecnic) REFERENCES TECNICS (DNItreballador);





